### ISSUE TITLE
Several directory

### ISSUE THREAD

**Issue by borodadada** [fastify/fastify-static#108]
Hello, how i can set several directory? I didn't see this example in doc.

try
```
fastify.register( require('fastify-static'), { root: path.join(__dirname, 'dist'), prefix: '/dist/' } )
fastify.register( require('fastify-static'), { root: path.join(__dirname, 'public'), prefix: '/public/' } )
```
Error

node_modules\fastify\lib\decorate.js:19
    throw new FST_ERR_DEC_ALREADY_PRESENT(name)

will great see array format
```
[
{ root: path.join(__dirname, 'dist1'), prefix: '/dist1/' },
{ root: path.join(__dirname, 'dist2'), prefix: '/dist2/' },
{ root: path.join(__dirname, 'dist3'), prefix: '/dist3/' }  
]
```

**Comment by mcollina** [comment]
You should disable the decorator: https://github.com/fastify/fastify-static#disabling-reply-decorator.

As for the multiple directory/array, would you like to send a PR?

**Comment by borodadada** [comment]
mcollina thanks man. Work!

```
fastify.register( require('fastify-static'), { root: path.join(__dirname, 'dist'), prefix: '/dist/', decorateReply: false } )
fastify.register( require('fastify-static'), { root: path.join(__dirname, 'public'), prefix: '/public/', decorateReply: false } )
```

**Comment by tapiamcclung** [comment]
Hi, I am very new to fastify so please bear with me. After reading #100 and this entry, I tried this and it worked earlier today, but all of the sudden I am getting:
```
     reply.sendFile('index.html')
            ^

TypeError: reply.sendFile is not a function
```
Any hints? I registered another path and it works, but how can I get the original path to work again?

**Comment by Eomm** [comment]
@tapiamcclung 
the `sendFile` is a decorator added by this plugin.

If you are calling this method in an encapulated context without the `fastify-static` plugin registered you will get that error.
So you have a context with this plugin and another context without. So you should move the registration of the plugin in a higher context or load it in the context without it.
If you have trouble doing so, please open a new issue with your code in order to help you better.

I'm closing this issue since @borodadada solved the problem 👍

**Comment by stefanocudini** [comment]
> As for the multiple directory/array, would you like to send a PR?

@mcollina  Is there any other contribution regarding this?
