### ISSUE TITLE
100% code coverage

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-static#134]
As titled

**Comment by anthonyringoet** [comment]
I was looking into this. Looking for a bit of feedback.

Missing lines are:
1. [157](https://github.com/fastify/fastify-static/blob/779ce813b48bf33a044ba300f53bca88c23f2fcd/index.js#L157): if `glob` throws an error
 It's hard to let `glob` throw because an invalid string will not match (and that's valid behavior). It's possible sending in a non-string value but fastify-static uses a default if it's not a string.

An option is to mock underlying used `fs` methods and let glob fail this way. Like `glob` does in their [own tests](https://github.com/isaacs/node-glob/blob/f5a57d3d6e19b324522a3fa5bdd5075fd1aa79d1/test/error-callback.js). This works but interested in feedback and alternatives.

2. [218](https://github.com/fastify/fastify-static/blob/779ce813b48bf33a044ba300f53bca88c23f2fcd/index.js#L218): if `statSync` throws an error that is not `ENOENT`

Options include ensuring statSync is actually mocked (need a dependeny to override this require I think?) or trying to let stat actually error with a non `ENOENT` error (which is quite hard as I've noticed!).

**Comment by mcollina** [comment]
Go ahead and add mocking with `proxyquire`.
