### ISSUE TITLE
render static file with route parameter 

### ISSUE THREAD

**Issue by astesio** [fastify/fastify-static#15]
I am using plugin [ponit-of-view](https://github.com/fastify/point-of-view) and[ fastify-static](https://github.com/fastify/fastify-static), I have a route for example : `fastify.get('/', function (request, reply) {
    reply.view('/index.ejs', { text: 'text' });
})` in the file index.ejs, I am importing a css file and js, it is work perfect. 

But when I change route for this example: `fastify.get('/:dynimic/route', function (request, reply) {
    reply.view('/index.ejs', { text: 'text' });
})`
I have a problem, see below.
`GET http://localhost:3000/astes/css/css.css net::ERR_ABORTED
GET http://localhost:3000/astes/js/console.js net::ERR_ABORTED`.

**Comment by allevo** [comment]
Hi!
How are you registering `fastify-static` and `point-of-view`? Could do you provide a simple code?

**Comment by astesio** [comment]
sure.
I am structure [here](https://imgur.com/a/G2LQz)
My [index.ejs](https://imgur.com/a/ehmYO)

**Comment by allevo** [comment]
Your assets are relative to the current url so the css is not found. 

Could you try to use `<link rel="stylesheet" href="/css/css.css">`?

**Comment by astesio** [comment]
Oh man, thanks so much, I had tried everything without success, But it is solutions was ridiculous. 
Was it is this ;).
I have other problem, but I do know it is problem is point-of-view, or mine.

I make a pock test with express solution it is work, but I tried with fastify don't work, includes partials. 
When I use `<% include head/head.ejs %>` or `<% include ./head/head.ejs %>` or `<% include head/head %>` or `<% include ./head/head %>` I  receive an error 

> Could not find include include file
I am anything wrong ?
But if you think it is better open other issue I am delete question.

**Comment by allevo** [comment]
If you are using relative paths, you should know which the base path is. Always. I don't know how the ejs template engine resolves the relative. Please check it's documentation out.

I don't understand if the problem explained above is resolved. If yes, please close the issue

**Comment by folmedov** [comment]
Hi! 

Sorry for reopening this topic, but in case it helps anyone, I was having the same error (net::ERR_ABORTED 500 (Internal Server Error)) when using a path with 2 dynamic parameters like /:a/:b, and the error is when defining the root path "/" to serve the static files, since the path that will be resolved when loading the static files will be of the type /css/styles. css which Fastify will interpret as a match for the path /:a/:b and was trying to resolve to that path.

I hope I'm not bothering anyone, but I spent quite a while trying to figure out what this error was due to.

Cheers!
