### ISSUE TITLE
Change the payload for every .html file

### ISSUE THREAD

**Issue by PeteSolid** [fastify/fastify-static#170]
How can I modify the payload for every .html file?

I already tried different hooks, but the payload is a stream and I am a bit clueless what is going on.

**Comment by mcollina** [comment]
You'd have to concat the stream and do the parsing/changing of every html file that pass through. As an example, you can use `concat-stream`.

**Comment by snapwich** [comment]
this actually seems impossible to do correctly i think, at least through the `onSend` hook. i can definitely transform the stream but it seems by the time the hook is called the headers have already been sent which means if my new content is longer than the original file the result will be truncated due to the content-length already being sent.

**Comment by Ethan-Arrowood** [comment]
I stumbled upon this issue while working on a new post: https://polar.sh/Ethan-Arrowood/posts/injecting-html-into-a-fastify-static-file-server

I believe this should help!
