### ISSUE TITLE
Feature Request: sendFile without serving anything

### ISSUE THREAD

**Issue by ilyaigpetrov** [fastify/fastify-static#20]
On my site each user has subdomain:
```
ilya.mysite.com/his/file
homer.mysite.com/index.html
```
I can't just tell `serve this folder`, I first retrieve username (homer), then serve his folder (users/homer). Ideally I would like to use `reply.sendFile(path)`, but couldn't do it without specifying `root` folder (and serving file I don't want to server). Would be nice to have `reply.sendFile` separately from everything else.

Thanks!

**Comment by allevo** [comment]
Hi!
Thank you for this suggestion.

Truly this plugin was born to serve static files in development mode: nodejs is not so good on serving static files. Use a reverse proxy like `nginx` or `haproxy`.

Anyway we can split this plugin in order to add `sendFile` method.  But I'd like to wait https://github.com/fastify/fastify/pull/466

**Comment by sarneeh** [comment]
This would be awesome! 👍

**Comment by mcollina** [comment]
Would you like to send a PR?

Basically you should add an option that makes https://github.com/fastify/fastify-static/blob/master/index.js#L94-L96 optional.

**Comment by sarneeh** [comment]
@mcollina Here you are 😄
