### ISSUE TITLE
Make extendedFolderInfo more selective

### ISSUE THREAD

**Issue by Eli-Nathan** [fastify/fastify-static#258]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.15.1

### Plugin version

4.5.0

### Node.js version

14

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

any

### Description

We're saving a bunch of response snapshots in a directory which we are then serving with Fastify Static.

Using the render method with `list.extendedFolderInfo` we're printing out some nice info on each subdirectory such as the time of the last modified file and how many folders it contains.

The directory is pretty big though, up to 10Gb sometimes.

Because of the size, it takes Node so long to compute the `dir.totalSize` property that it always results in a timeout and the CPU on our box goes on fire. We have a bunch of dirs, and some contain hundreds of files.

Is there a way we could make the extendedFolderInfo more selective so we can choose which items it computes? This would mean we can use certain properties without it computing them all and timing out.

### Steps to Reproduce

Create a dir to list with a lot of content in it.

Try to render the list of dir/files using the extendedFolderInfo prop on list.

Watch timeout occur because computing the size is too expensive.

### Expected Behavior

We'd be able to use _some_ extended folder info without it computing values for all the properties

**Comment by mcollina** [comment]
I think you are seeing some _different_ behavior than what you are describing.

Take a look at https://github.com/fastify/fastify-static/blob/ad66ca18230e1a565513eefaa8cad008c13b2b65/lib/dirList.js#L40-L87.
This code does not read the full files, nor it's influenced by the files size, only by their number.
 
Anyway I don't think there is much we can do on this regard as the cost is reading the file stats, not doing any computation on top: skipping some fields is not going to change much as that information has already been read from the OS.

The only solution to this problem is caching and computing some "approximate" amounts.
